org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m
org.gradle.daemon=false
android.useAndroidX=true
android.overridePathCheck=true
# Debug symbol configuration
android.debugSymbolFormat=dwarf
android.bundleConfig.enableSplit=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
